name: Update TMC Articleon:
  push:
    branches: [ main ]:
  update-tmc-article:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies for TMC Article Update Action
      run: sudo apt update && sudo apt install -y jq gawk
      shell: bash

    - uses: gamemann/tmc-api-article@v1.0.0
      with:
        tmc_api_url: ${{ secrets.TMC_API_URL }}
        tmc_api_key: ${{ secrets.TMC_API_KEY }}
        tmc_article_id: ${{ secrets.TMC_ARTICLE_ID }}
